Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load dataloader
dataloader_config_fpath = os.path.join(config['dataloader_config_folder'], dataloader_ID)

# Data loader
print("\nSetting up the data loader with config file: {}\n\n".format(dataloader_ID))
dataloader = IceNetDataLoader(dataloader_config_fpath)
print('\n\nDone.\n')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_8971/1698764756.py[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0;31m# Data loader[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mprint[0m[0;34m([0m[0;34m"\nSetting up the data loader with config file: {}\n\n"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mdataloader_ID[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0mdataloader[0m [0;34m=[0m [0mIceNetDataLoader[0m[0;34m([0m[0mdataloader_config_fpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0mprint[0m[0;34m([0m[0;34m'\n\nDone.\n'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/environmental-ds-book/environmental-ds-book/book/polar/modelling/polar-modelling-icenet/icenet/utils.py[0m in [0;36m__init__[0;34m(self, dataloader_config_fpath, seed)[0m
[1;32m    703[0m         [0mself[0m[0;34m.[0m[0mset_variable_path_formats[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    704[0m         [0mself[0m[0;34m.[0m[0mset_number_of_input_channels_for_each_input_variable[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 705[0;31m         [0mself[0m[0;34m.[0m[0mload_polarholes[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    706[0m         [0mself[0m[0;34m.[0m[0mdetermine_tot_num_channels[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    707[0m         [0mself[0m[0;34m.[0m[0mon_epoch_end[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/environmental-ds-book/environmental-ds-book/book/polar/modelling/polar-modelling-icenet/icenet/utils.py[0m in [0;36mload_polarholes[0;34m(self)[0m
[1;32m    965[0m [0;34m[0m[0m
[1;32m    966[0m         [0mpolarhole_path[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mjoin[0m[0;34m([0m[0mconfig[0m[0;34m.[0m[0mmask_data_folder[0m[0;34m,[0m [0mconfig[0m[0;34m.[0m[0mpolarhole1_fname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 967[0;31m         [0mself[0m[0;34m.[0m[0mpolarhole1_mask[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mpolarhole_path[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    968[0m [0;34m[0m[0m
[1;32m    969[0m         [0mpolarhole_path[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mjoin[0m[0;34m([0m[0mconfig[0m[0;34m.[0m[0mmask_data_folder[0m[0;34m,[0m [0mconfig[0m[0;34m.[0m[0mpolarhole2_fname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/lib/python3.8/site-packages/numpy/lib/npyio.py[0m in [0;36mload[0;34m(file, mmap_mode, allow_pickle, fix_imports, encoding)[0m
[1;32m    415[0m             [0mown_fid[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m    416[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 417[0;31m             [0mfid[0m [0;34m=[0m [0mstack[0m[0;34m.[0m[0menter_context[0m[0;34m([0m[0mopen[0m[0;34m([0m[0mos_fspath[0m[0;34m([0m[0mfile[0m[0;34m)[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    418[0m             [0mown_fid[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    419[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/masks/polarhole1_mask.npy'
FileNotFoundError: [Errno 2] No such file or directory: 'data/masks/polarhole1_mask.npy'

